# This is a basic workflow to help you get started with Actions

name: Zip And Release Sample

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    tags:
      - v*

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # 自訂的變數:取得最後一筆commit訊息
    env:
      # 使用該次push commit最後一條訊息
      # release_title: ${{github.event.head_commit.message}}
      release_title: ${{github.ref}}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Get the version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\/}
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          echo ${{env.VERSION}}

      - name: Install zip package
        uses: montudor/action-zip@v1
      - name: Zip
        working-directory: ConsoleApp
        run: zip -qq -r ${{env.release_title}}.zip Production

      - name: Upload Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{env.release_title}}
          prerelease: false
          files: ConsoleApp/${{env.release_title}}.zip
